server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: patient-service
  
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

# Activation de l'Actuator pour le healthcheck Docker
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always